services:
  app:
    build: .
    container_name: blackjack-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql-db:3306/blackjack
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=root
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/blackjack
    depends_on:
      mysql-db:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - blackjack-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=blackjack
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - blackjack-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - blackjack-network

networks:
  blackjack-network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
